### ISSUE TITLE
removed-in and versionremoved not recognized

### ISSUE THREAD

**Issue by nicoddemus** [MrSenko/sphinx-removed-in#3]
Hi,

I'm trying to use this extension in pytest (https://github.com/pytest-dev/pytest/pull/4570). 

I've added `sphinx_removed_in` to the list of extensions in `conf.py`, and used the directive like this in the docs:

```rst
.. removed-in:: 4.0
```

I'm getting this error while building the documentation:

```
Exception occurred:
  File "c:\users\bruno\pytest\.tox\docs\lib\site-packages\sphinx\domains\changeset.py", line 72, in run
    text = versionlabels[self.name] % self.arguments[0]
KeyError: 'removed-in'
```

Same error if I use `versionremoved`.

(Here's the full log: [sphinx-err-p7jio8jd.log](https://github.com/MrSenko/sphinx-removed-in/files/2702822/sphinx-err-p7jio8jd.log))

Here are the packages/versions installed to generate the docs:

```
docs installed: alabaster==0.7.12,atomicwrites==1.2.1,attrs==18.2.0,Babel==2.6.0,certifi==2018.11.29,chardet==3.0.4,colorama==0.4.1,docutils==0.14,hypothesis==3.84.4,idna==2.8,imagesize==1.1.0,Jinja2==2.10,MarkupSafe==1.1.0,more-itertools==4.3.0,nose==1.3.7,packaging==18.0,pluggy==0.8.0,py==1.7.0,Pygments==2.3.1,pygments-pytest==1.1.0,pyparsing==2.3.0,-e git+git@github.com:nicoddemus/pytest.git@fe01b9e62aaca64f3a5ec77f21452c65b9ee55e5#egg=pytest,pytz==2018.7,requests==2.21.0,six==1.12.0,snowballstemmer==1.2.1,Sphinx==1.8.2,sphinx-removed-in==0.1.2,sphinxcontrib-trio==1.0.1,sphinxcontrib-websupport==1.1.0,urllib3==1.24.1
```

The sphinx-related ones are:

```
Sphinx==1.8.2
sphinx-removed-in==0.1.2
sphinxcontrib-trio==1.0.1
sphinxcontrib-websupport==1.1.0
```

Anything else I should be doing for Sphinx to recognize the new directive?

Thanks!

**Comment by atodorov** [comment]
Can you try the latest master branch? I've added some tests and during testing updated because of a deprecation warning which produced similar issue like yours. If this fixes the problem for you I will release a new version.

**Comment by nicoddemus** [comment]
Hi, thanks and sorry for the delay, I was out in the holidays.

It does work now with the master branch, thanks! Would appreciate if you could ping me here when the next release is out. 👍

**Comment by atodorov** [comment]
0.1.3 is pushed to PyPI.

> Would appreciate if you could ping me here when the next release is out.

Use pyup.io for this.

**Comment by nicoddemus** [comment]
Oh that was quick, awesome. Thanks a lot! I will keep pyup.io in mind for the documentation requirement, seems like a good idea.
